global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: itsc-quickstart
  regions:
    - us-east-1
    - us-west-2
    - eu-west-1
  reporting: true
tests:
  test-kinesis:
    parameter_input: connector-test-kinesis-kp.json
    template_file: kepware-industrial-data-connector-master.yaml
    regions:
      - us-east-1
      - us-west-2
      - eu-west-1
