global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: itsc-quickstart
  regions:
    - us-east-1
     - us-west-2
     - us-east-2
     - eu-central-1
     - eu-west-1
     - eu-west-2
     - ap-southeast-1
     - ap-southeast-2
     - ap-northeast-1
     - ap-northeast-2
  reporting: true
tests:
  test-iot:
    parameter_input: connector-test-iot-pi.json
    template_file: pi-industrial-data-connector-master.yaml
    regions:
      - us-east-1
      - us-west-2
      - us-east-2
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ap-northeast-2
